[package]
name = "pdf2text"
version = "0.1.0"
authors = ["idle <idle@outlook.com>"]
edition = "2018"

[dependencies]
pdf-extract = ""
lopdf = "0.15.3"

[profile.release]
panic = 'abort'
lto = true
opt-level = "z"